project:
  type: website

website:
  title: "Platynereis cell-type compendium"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    smooth-scroll: true
    css: styles.css
    toc: true

editor: source

