s/prototroch_1clock_A/prototroch_2A/g
s/prototroch_1clock_P/prototroch_2P/g
s/prototroch_2clock_A/prototroch_3A/g
s/prototroch_2clock_P/prototroch_3P/g
s/prototroch_3clock_A/prototroch_4A/g
s/prototroch_3clock_P/prototroch_4P/g
s/prototroch_4clock_A/prototroch_5A/g
s/prototroch_4clock_P/prototroch_5P/g
s/prototroch_5clock_A/prototroch_6A/g
s/prototroch_5clock_P/prototroch_6P/g
s/prototroch_6clock_A/prototroch_7A/g
s/prototroch_6clock_P/prototroch_7P/g
s/prototroch_7clock_A/prototroch_8A/g
s/prototroch_7clock_P/prototroch_8P/g
s/prototroch_8clock_A/prototroch_9A/g
s/prototroch_8clock_P/prototroch_9P/g
s/prototroch_9clock_A/prototroch_10A/g
s/prototroch_9clock_P/prototroch_10P/g
s/prototroch_10clock_A/prototroch_11-12A/g
s/prototroch_10clock_P/prototroch_11P/g
s/prototroch_11clock/prototroch_12P/g
s/prototroch_12clock_A/prototroch_1A/g
s/prototroch_12clock_P/prototroch_1P/g
